# travis.yml for testing radare2. Initially written in 2014-2016, by jn__.

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

matrix:
  exclude:
      - os: osx
        compiler: gcc

sudo: false

addons:
  apt:
    packages:
      - dc
      - binutils
      - cabextract
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

cache:
  - ccache
  - apt

script:
  - git clone --depth 1 `doc/repo REGRESSIONS`
  - ./configure --prefix=`pwd`/install
  # - make -s -j2 > /dev/null
  - make -j2
  - make install
  - export PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/pkgcfg:${PKG_CONFIG_PATH}
  - export PATH=${TRAVIS_BUILD_DIR}/install/bin:${PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib:${LD_LIBRARY_PATH}
  - export NOOK=1
  - export NOREPORT=1
  - make -C libr unittest
  - cd radare2-regressions
  - VERBOSE=1 make -k all || exit 0
