name: CI

on:
  push:
    branches:
    - master
    - '*asan*'
    - '*centos*'
    - '*static*'
  schedule:
    - cron: '0 18 * * 1,3,5' # Three-weekly at 18:00 UTC on Monday, Wednesday, and Friday
  pull_request:
    branches:
    - master

jobs:
  # TODO: add build check for capstone 3
  # TODO: add build check for capstone 4
  # TODO: add build check for capstone 5
  # TODO: build r2-bindings

  build-and-test:
    name: ${{ matrix.name }}-tests-${{ matrix.run_tests }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        name: [linux-acr-gcc, linux-acr-clang, linux-meson-gcc, linux-meson-gcc-newshell, macos-clang]
        include:
          - name: linux-acr-gcc
            os: ubuntu-latest
            build_system: acr
            compiler: gcc
            run_tests: true
          - name: linux-acr-clang
            os: ubuntu-latest
            build_system: acr
            compiler: clang
            run_tests: ${{ github.event_name == 'push' }}
          - name: linux-meson-gcc
            os: ubuntu-latest
            build_system: meson
            compiler: gcc
            meson_options: -Db_coverage=true
            coverage: ${{ github.event_name == 'push' }}
            run_tests: ${{ github.event_name == 'push' }}
          - name: linux-meson-gcc-newshell
            os: ubuntu-latest
            build_system: meson
            compiler: gcc
            newshell: true
            run_tests: true
          - name: macos-clang
            os: macos-latest
            build_system: acr
            compiler: clang
            run_tests: true

    steps:
    - uses: actions/checkout@v2
    - name: Install pkg-config with Homebrew
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config
    - name: Install python
      if: (matrix.run_tests || matrix.build_system == 'meson') && matrix.os != 'macos-latest'
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools
    - name: Install meson and ninja
      if: matrix.build_system == 'meson'
      run: pip3 install --user meson==0.52.0 ninja==1.10.0
    - name: Install test dependencies
      if: matrix.run_tests
      run: pip3 install --user 'git+https://github.com/radareorg/radare2-r2pipe#egg=r2pipe&subdirectory=python'
    - name: Install clang
      if: matrix.compiler == 'clang' && matrix.os == 'ubuntu-latest'
      run: sudo apt-get --assume-yes install clang
    - name: Checkout our Testsuite Binaries
      uses: actions/checkout@v2
      with:
          repository: radareorg/radare2-testbins
          path: test/bins
    - name: Configure with ACR and build
      if: matrix.build_system == 'acr'
      run: ./configure --prefix=${HOME} && make
      env:
        CC: ${{ matrix.compiler }}
    - name: Build with Meson
      if: matrix.build_system == 'meson'
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        meson --prefix=${HOME} build && ninja -C build
      env:
        CC: ${{ matrix.compiler }}
    - name: Install with make
      if: matrix.build_system == 'acr'
      run: |
        # Install the radare2
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        make install
    - name: Install with meson
      if: matrix.build_system == 'meson'
      run: |
        # Install the radare2
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        ninja -C build install
    - name: Run tests
      if: matrix.run_tests
      run: |
        # Running the test suite
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        if [ "$NEWSHELL" == "true" ]; then
          export R2_CFG_NEWSHELL=1
        fi
        cd test
        radare2 -N -Qc 'e cfg.newshell' -
        make
      env:
        NEWSHELL: ${{ matrix.newshell }}
    - name: Upload coverage info
      uses: codecov/codecov-action@v1
      if: matrix.coverage == '1'

  build-centos6:
    name: Build CentOS 6
    runs-on: ubuntu-latest
    if: contains(github.ref, 'centos') || contains(github.ref, 'release-') || github.event_name == 'schedule'
    container: centos:6
    steps:
    - name: Install tools
      run: yum install -y patch unzip git gcc make
    - name: Checkout r2
      run: |
        git clone https://github.com/${{ github.repository }}
        cd radare2
        git fetch origin ${{ github.ref }}
        git checkout -b local_branch FETCH_HEAD
    - name: Configure with ACR and build
      run: ./configure --prefix=/usr && make CS_RELEASE=1
      working-directory: radare2
    - name: Install with make
      run: make install
      working-directory: radare2
    - name: Run tests
      run: cd test/unit && make
      working-directory: radare2
      env:
        # `make install` installs, for some unknown reasons, pkgconfig files in
        # /usr/lib and not in /usr/lib64, thus pkg-config cannot find the right
        # .pc files if the right path is not specified
        PKG_CONFIG_PATH: /usr/lib/pkgconfig
