name: Continuous build
on:
  push:
    branches:
      - master

jobs:
  build-continuous-deb:
    name: Continuous deb build
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - name: Install tools
      run: apt-get update && apt-get install --yes patch unzip git gcc make curl pkg-config xz-utils wget file
    - name: Checkout r2
      run: |
        git clone https://github.com/${{ github.repository }}
        cd radare2
        git fetch origin ${{ github.ref }}
        git checkout -b local_branch FETCH_HEAD
    - name: Preparing the deb package
      run: |
        sys/debian.sh
        mv radare2_*_amd64.deb ../
        mv radare2-dev_*_amd64.deb ../
      working-directory: radare2
    - name: Upload deb file
      uses: actions/upload-artifact@v2
      with:
        path: radare2_*_amd64.deb
    - name: Upload -dev deb file
      uses: actions/upload-artifact@v2
      with:
        path: radare2-dev_*_amd64.deb
