name: Windows

on:
  push:
    branches:
    - '*windows*'

jobs:
  build:
    name: windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
          vs-version: 15.9
    - name: Install meson and ninja
      run: '%PYTHON%\python.exe -m pip install meson ninja'
