name: Windows

on:
  push:
    branches:
    - '*windows*'

jobs:
  build:
    name: windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja
    - name: print stuff
      run: vswhere.exe -prerelease -latest -property installationPath
    - name: meson setup
      run: |
        .github\vsdevenv.bat
        meson build --backend vs2019
        msbuild build\radare2.sln
#      env:
#        CC: cl
#        CXX: cl
